ALTER TABLE employees
ADD COLUMN email VARCHAR(255);


ALTER TABLE table_name
DROP COLUMN column_name;


--REMANE COLUMN NAME
ALTER TABLE EMPLOYEES 
RENAME COLUMN EMAIL TO MAILE
-- REMANE TABLE NAME
ALTER TABLE EMPLOYEES 
RENAME TO MYEMPLOYEES